apiVersion: skaffold/v2alpha1
kind: Config
metadata:
  name: webflux-todo
build:
  artifacts:
  - image: gcr.io/abekoh-sand/webflux-todo
    jib: 
      args:
        - -DskipTests
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
