apiVersion: v1
kind: Service
metadata:
  name: webflux-todo
  labels:
    app: webflux-todo
  namespace: todo
spec:
  selector:
    app: webflux-todo
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  loadBalancerIP: 35.208.115.61
