name: Build and deploy to GKE
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '275.0.0'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Gcloud setting
        run: |
          gcloud components install docker-credential-gcr
          docker-credential-gcr config -token-source="gcloud"
          gcloud auth configure-docker
      - name: Setup skaffold
        run: |
          # https://skaffold.dev/docs/install/
          curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64
          chmod +x skaffold
          sudo mv skaffold /usr/local/bin
      - name: Cache maven modules
        uses: actions/cache@v1
        with:
          path: /root/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build and Deploy
        run: skaffold run
