name: Maven test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: mysql
    container:
      image: maven:3.6.3-jdk-11
      env:
        SPRING_R2DBC_URL: r2dbc:mysql://mysql:3306/todo
    steps:
    - uses: actions/checkout@v1
    - name: Cache maven modules
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Create database schema
      run: mysql --host mysql --port 3306 -uroot -pmysql -e "CREATE DATABASE todo;"
    - name: Test with Maven
      run: mvn -B test --file pom.xml
