name: Maven test

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: maven:3.6.3-jdk-11
    steps:
    - uses: actions/checkout@v1
    - name: Cache maven modules
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Test with Maven
      run: mvn -B test --file pom.xml
